#!/usr/bin/env python3
“”“Usage: python vault_mini.py {show|get current|get previous|tag N M|rotate N} secret/ma-cle”””
import os, sys, hvac

c = hvac.Client(url=os.environ[“VAULT_ADDR”], token=os.environ[“VAULT_TOKEN”])
cmd, path, *args = sys.argv[1:]
mount, key = path.split(”/”, 1)

kv = c.secrets.kv.v2
meta = lambda: kv.read_secret_metadata(path=key, mount_point=mount)[“data”]
tag = lambda cur, prev: kv.update_metadata(path=key, mount_point=mount,
custom_metadata={“stable_current”: str(cur), “stable_previous”: str(prev)})

if cmd == “show”:
m = meta(); cm = m.get(“custom_metadata”) or {}
print(f”v{m[‘current_version’]} | current=v{cm.get(‘stable_current’,’?’)} previous=v{cm.get(‘stable_previous’,’?’)}”)
elif cmd == “get”:
v = (meta().get(“custom_metadata”) or {})[f”stable_{args[0]}”]
print(kv.read_secret_version(path=key, version=int(v), mount_point=mount)[“data”][“data”])
elif cmd == “tag”:
tag(args[0], args[1])
elif cmd == “rotate”:
tag(args[0], (meta().get(“custom_metadata”) or {})[“stable_current”])