#!/usr/bin/env python

# -*- coding: utf-8 -*-

“”“Usage: python vault_mini.py {show|get current|get previous|tag N M|rotate N} secret/ma-cle”””
import os, sys, hvac

c = hvac.Client(url=os.environ[“VAULT_ADDR”], token=os.environ[“VAULT_TOKEN”])
args = sys.argv[1:]
cmd, path = args[0], args[1]
extra = args[2:]
mount, key = path.split(”/”, 1)

kv = c.secrets.kv.v2

def meta():
return kv.read_secret_metadata(path=key, mount_point=mount)[“data”]

def tag(cur, prev):
kv.update_metadata(path=key, mount_point=mount,
custom_metadata={“stable_current”: str(cur), “stable_previous”: str(prev)})

if cmd == “show”:
m = meta()
cm = m.get(“custom_metadata”) or {}
print(“v{0} | current=v{1} previous=v{2}”.format(
m[“current_version”], cm.get(“stable_current”, “?”), cm.get(“stable_previous”, “?”)))
elif cmd == “get”:
cm = meta().get(“custom_metadata”) or {}
v = cm[“stable_” + extra[0]]
print(kv.read_secret_version(path=key, version=int(v), mount_point=mount)[“data”][“data”])
elif cmd == “tag”:
tag(extra[0], extra[1])
elif cmd == “rotate”:
cm = meta().get(“custom_metadata”) or {}
tag(extra[0], cm[“stable_current”])